type TalentMember = {
  name: string;
  title: string;
  bio?: string;
  skills: Array<string>;
  portfolioLink: string;
  imageSrc: string;
};

export const talentMembers: Array<TalentMember> = [
  {
    name: "Lia Moua",
    title: "Full-Stack Software Engineer",
    bio: "I'm a full-stack software engineer with a background in criminal justice. Pretty interesting and a story to tell! I am career transitioning to software engineering and development. With my prior experiences in criminal justice, I'm always a team player. I enjoy working in teams to solve challenges and problems. I'm a leader who encourages and helps my team to excel. I enjoy the continuation of learning because learning allows me to advance my knowledge in areas where it’s needed. I'm currently looking for software engineering/development opportunities.",
    skills: [
      "Javascript",
      "HTML",
      "CSS",
      "React",
      "SQLite",
      "SQL",
      "Express",
      "NodeJS",
      "PostgreSQL",
      "Java",
      "C#",
      ".NET Core",
      "Automation Testing",
      "Quality Assurance",
    ],
    portfolioLink: "https://github.com/moua0061",
    imageSrc: "/images/talent/lia-moua.jpeg",
  },
  {
    name: "Alex Curtis-Slep",
    title: "Front-End Developer",
    bio: "Web developer and a multi-hackathon winner with a solid background in content creation. Curious and fast learner. As a bilingual Cuban immigrant with strong skills in problem-solving and effective communication, I believe technology is a natural continuation of my love for ﬁnding solutions and creatively building products that communicate value and help people.",
    skills: [
      "React",
      "Vue",
      "JavaScript",
      "Node",
      "Express",
      "CSS3",
      "SCSS",
      "HTML5",
    ],
    portfolioLink: "https://alexcurtisslep.com",
    imageSrc: "/images/talent/alex-curtis.jpg",
  },
  {
    name: "Jody VanHoose",
    title: "Product Designer + Front-End Developer",
    bio: `Hello, my name is Jody VanHoose. I am a Front End Web Developer who graduated from Code Kentucky Bootcamp. I have always had a passion for working and tinkering with tech. As I am also a Physical Therapist Assistant with many years of experience in healthcare, I bring many other qualifications with me like good oral and written communication, collaboration with interdisciplinary teams, and problem-solving. I am currently in a leadership role and work well with other teammates. In addition to my current physical therapy duties, I am the unofficial "IT guy" for our facility. I'm excited to learn more and grow as a Front End Web Developer and I can't wait to be a part of your team and help solve tomorrow’s problems today!`,
    skills: [
      "SASS",
      "Bootstrap",
      "Tailwind CSS",
      "Skeleton CSS",
      "JavaScript",
      "React js",
      "Figma Design software",
      "Git",
      "GitHub",
      "NPM",
    ],
    portfolioLink: "https://jodyvanhoose.com/",
    imageSrc: "/images/talent/jody-vonhoose.png",
  },
  {
    name: "Andrea Everett",
    title: "Product Designer + Front-End Developer",
    bio: `My name is Andrea Everett. I am a Web Developer with experience in HTML5/CSS, Javascript, and React. Knowledge of backend tools, such as Express.js, Node.js, and Postgres SQL to further support web-building process. Quick learner, efficient problem-solver, and organized. Eager to continually grow in knowledge and coding-efficiency.`,
    skills: [
      "Javascript",
      "Typescript",
      "HTML",
      "CSS",
      "React Native",
      "ReactJS",
      "Redux",
      "Firebase",
      "Express",
      "Jira",
      "GIT",
    ],
    portfolioLink: "https://www.andreaeverett.dev/",
    imageSrc: "/images/talent/andrea-everett.png",
  },
  {
    name: "Malcolm Lowery",
    title: "App + Web + Mobile Developer",
    bio: `I enjoy solving problems and experimenting when presented with an unknown. I am a motivated team player who also works well independently with minimal oversight. I operate with the mentality that every day is an opportunity to learn something new.`,
    skills: [
      "HTML5/CSS",
      "Javascript",
      "React",
      "Express.js",
      "Node.js",
      "Postgres SQL",
    ],
    portfolioLink: "https://malcolmlowery.github.io/",
    imageSrc: "/images/talent/malcolm-lowery.jpg",
  },
  {
    name: "Steven Smodish",
    title: "Software Engineer",
    skills: [
      "JavaScript",
      "Python",
      "PHP",
      "C",
      "Java",
      "SQL",
      "React",
      "Express",
      "Next.js",
      "MaterialUI",
      "Node",
      "Firebase",
      "SASS",
      "Bootstrap",
      "Git/Github",
    ],
    portfolioLink: "https://github.com/ssmodish",
    imageSrc: "/images/talent/steve-smodish.jpg",
  },
  {
    name: "Zephyr Pfeiffer",
    title: "Software Engineer",
    bio: `My name is Zephyr Pfeiffer. I’m a meticulous software engineer who enjoys puzzle solving and a musician who loves to be creative. Ever since I was young, I have had an immense interest in video games. Video games inspired me to learn more about programming to create and implement my ideas into working applications. \n\n I relish the scenarios where I can come up with a creative and efficient solution to a difficult problem. I am always looking to test my skills further to improve my programming abilities and create applications that will be used in real-life scenarios.`,
    skills: [
      "HTML/CSS",
      "JavaScript",
      "Node.js",
      "Express",
      "MongoDB",
      "React",
      "NextJS",
    ],
    portfolioLink: "https://zephyrpfeiffer.netlify.app/",
    imageSrc: "/images/talent/zephyr-pfeiffer.jpg",
  },
  {
    name: "Jasmin Villatoro",
    title: "Product Designer + Front-End Developer",
    bio: `Hello! My name is Jasmin, I'm a Frontend Web Developer who loves to code beautiful interfaces with HTML, CSS, JavaScript, and Reactjs. I've created multiple UI projects as well as collaborated with other software developers. I'm an open-minded individual who loves learning new technologies.`,
    skills: ["ReactJS", "HTML5", "CSS3", "JavaScript"],
    portfolioLink: "https://www.jasminvillatoroportfolio.com/",
    imageSrc: "/images/talent/jasmin-villatoro.jpg",
  },
];
